title: "Substack Import Site"
description: "Converted blog posts for Substack import"
timezone: "America/New_York"

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
    source: html_posts

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

feed:
  path: feed.xml
  collections:
    - posts

exclude:
  - "_posts/"
  - "md2html.py"
  - "README.md"
  - ".jekyllignore"

theme: minima
