title: My GitHub Pages Site
description: "Temporary site for Substack import"
baseurl: "" # leave empty if site is at root
url: "https://schlice.github.io/substack-import" # change to your repo URL

# Define custom collection for posts
collections:
  html_posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed

# Feed configuration
feed:
  collections:
    - html_posts
  posts_limit: 1500  # smaller = faster builds

# Markdown processor
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# No theme (we’re using a raw HTML index)
theme: null

# Folders/files Jekyll should not process
exclude:
  - _posts
  - _html_posts_backups
  - html_posts_by_year
  - fix_frontmatter.py
  - fix_frontmatter2.py
  - split_posts_by_year.py
  - year_deploy.py
